featureGates:
  GatewayAPI: false

replicaCount: 1

image:
  repository: projects.registry.vmware.com/ako/ako
  pullPolicy: IfNotPresent
  pullSecrets: []

GatewayAPI:
  image:
    repository: projects.registry.vmware.com/ako/ako-gateway-api
    pullPolicy: IfNotPresent

AKOSettings:
  primaryInstance: true   
  enableEvents: 'true'
  logLevel: WARN
  fullSyncFrequency: '1800'
  apiServerPort: 8080
  deleteConfig: 'false' 
  disableStaticRouteSync: 'false'
  clusterName: 'tkc-cluster-1'
  cniPlugin: 'antrea'
  enableEVH: false
  layer7Only: true
  namespaceSelector:
    labelKey: ''
    labelValue: ''
  servicesAPI: false 
  vipPerNamespace: 'false'
  istioEnabled: false
  blockedNamespaceList: []
  ipFamily: ''
  useDefaultSecretsOnly: 'false'
NetworkSettings:
  nodeNetworkList: []
  enableRHI: false
  nsxtT1LR: ''
  bgpPeerLabels: []
  vipNetworkList: []
L7Settings:
  defaultIngController: 'true'
  noPGForSNI: false 
  serviceType: NodePortLocal
  shardVSSize: SMALL
  passthroughShardSize: SMALL
  enableMCI: 'false'

L4Settings:
  defaultDomain: ''
  autoFQDN: default   

ControllerSettings:
  serviceEngineGroupName: domain-c1006:5de34cdc-8b14-46a3-b1c9-b627d574cdf0
  controllerVersion: '22.1.5'
  cloudName: nsx-t
  controllerHost: ''
  tenantName: admin

nodePortSelector:
  key: ''
  value: ''

resources:
  limits:
    cpu: 350m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 300Mi

securityContext: {}

podSecurityContext: {}

rbac:
  pspEnable: false


avicredentials:
  username: ''
  password: ''
  authtoken:
  certificateAuthorityData:


persistentVolumeClaim: ''
mountPath: /log
logFile: avi.log
akoGatewayLogFile: avi-gw.log

