apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-app-cm.yaml
- argocd-job.yaml
- antrea-config.yaml
- tkgs-cluster-class-noaz.yaml

namespace: ns-1

images:
- name: whoami6443/argocd-hook
  newName: whoami6443/argocd-hook
