---
apiVersion: cni.tanzu.vmware.com/v1alpha1
kind: AntreaConfig
metadata:
  name: tkc-cluster-1-antrea-package
  namespace: ns-1
spec:
  antrea:
    config:
      antreaProxy:
        proxyLoadBalancerIPs: true
      defaultMTU: ""
      disableTXChecksumOffload: false
      disableUdpTunnelOffload: false
      dnsServerOverride: ""
      enableBridgingMode: false
      enableUsageReporting: false
      featureGates:
        AntreaIPAM: false
        AntreaPolicy: true
        AntreaProxy: true
        AntreaTraceflow: true
        Egress: true
        EndpointSlice: true
        FlowExporter: false
        Multicast: false
        Multicluster: false
        NetworkPolicyStats: true
        NodePortLocal: true
        SecondaryNetwork: false
        ServiceExternalIP: false
        TopologyAwareHints: false
        TrafficControl: false
      flowExporter:
        activeFlowTimeout: 60s
        collectorAddress: flow-aggregator/flow-aggregator:4739:tls
      noSNAT: false
      tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384
      trafficEncapMode: encap
      tunnelCsum: false
      tunnelPort: 0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tkc-cluster-1
  namespace: ns-1
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["192.168.32.0/20"]
    pods:
      cidrBlocks: ["192.168.0.0/20"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.26.5---vmware.2-fips.1-tkg.1
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 1
    variables:
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: vsan-default-storage-policy
      - name: defaultStorageClass
        value: vsan-default-storage-policy
# ADDITIONAL VALUES
      - name: nodePoolVolumes
        value:
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/containerd"
          name: containerd
          storageClass: vsan-default-storage-policy
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/kubelet"
          name: kubelet
          storageClass: vsan-default-storage-policy
      - name: controlPlaneVolumes
        value:
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/containerd"
          name: containerd
          storageClass: vsan-default-storage-policy
        - capacity:
            storage: "15Gi"
          mountPath: "/var/lib/kubelet"
          name: kubelet
          storageClass: vsan-default-storage-policy
