apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tkc-addons-${CLUSTER_NAME}
spec:
  project: default
  source:
    repoURL: ${TKC_ADDON_GIT}
    path: ${TKC_ADDON_GIT_FOLDER}
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: ${CLUSTER_IP}
  syncPolicy:
    automated:
      prune: true