apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tkc-addons-${CLUSTER_NAME}
spec:
  project: default
  source:
    repoURL: 'https://github.com/papivot/argocd-gitops-tanzu.git'
    path: tkc-addons
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: ${CLUSTER_IP}
  syncPolicy:
    automated:
      prune: true