apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-tkc-creation-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: argocd-tkc-post
        image: whoami6443/argocd-hook:0.1.1
        command: 
          - "/script.sh"
        env:
        - name: TKC_NAME
          value: "workload-vsphere-tkg1"
        - name: TKC_ADDON_GIT
          value: "https://github.com/papivot/argocd-gitops-tanzu.git"
        - name: TKC_ADDON_GIT_FOLDER
          value: "tkc-addons"
      restartPolicy: Never
      serviceAccountName: argocd-hook
  backoffLimit: 2
